apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: dipesh017/demo:result

