apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-frontend
  template:
    metadata:
      name: httpd-frontend
      labels:
        app: httpd-frontend
    spec:
      containers:
      - name: httpd 
        image: httpd:2.4-alpine
